import "fake-indexeddb/auto";
import {beforeEach,describe,expect,it,vi} from "vitest";

const recognize=vi.fn(),terminate=vi.fn(async()=>undefined),createWorker=vi.fn(async(_language:string,_oem:unknown,options:{logger:(message:{status:string;progress:number})=>void})=>({recognize:async(blob:Blob)=>{options.logger({status:"recognizing text",progress:.5});return recognize(blob)},terminate}));
vi.mock("tesseract.js",()=>({createWorker}));

import {db,now,uid} from "../src/data/db";
import {getOrCreateOcrRecord,saveImage,saveOcrRecord} from "../src/data/operations";
import {enqueueOcr} from "../src/services/ocr";
import {combinedOcrDocument,confirmedCombinedOcrText,prepareScreenshotOcr,recoverInterruptedOcr,runSequentialOcr,screenshotHash} from "../src/services/ocr-batch";
import type {Recipe,StoredImage} from "../src/data/types";

const setup=async()=>{
  const recipe:Recipe={id:uid(),name:"OCR",status:"untried",description:"",ingredients:[],steps:[],categoryIds:[],tagIds:[],sourceType:"screenshot",sourceUrl:"",rawText:"",normalizedText:"",coverImageId:null,createdAt:now(),updatedAt:now(),deletedAt:null,syncStatus:"local_only",revision:0};
  const image:StoredImage={id:uid(),recipeId:recipe.id,cookRecordId:null,stepId:null,type:"source",blob:new Blob(["png"],{type:"image/png"}),thumbnailBlob:new Blob(["thumb"],{type:"image/png"}),mimeType:"image/png",width:1,height:1,note:"",sortOrder:0,createdAt:now(),updatedAt:now(),syncStatus:"local_only"};
  await db.recipes.add(recipe);await saveImage(image);return{recipe,image};
};
const setupMany=async(count:number)=>{
  const {recipe}=await setup(),images:StoredImage[]=[];
  await db.images.clear();
  for(let index=0;index<count;index++){const image:StoredImage={id:uid(),recipeId:recipe.id,cookRecordId:null,stepId:null,type:"source",blob:new Blob(["image-"+index],{type:"image/png"}),thumbnailBlob:new Blob(["thumb-"+index],{type:"image/png"}),mimeType:"image/png",width:1,height:1,note:"",sortOrder:index,createdAt:now(),updatedAt:now(),syncStatus:"local_only"};await saveImage(image);images.push(image)}
  await prepareScreenshotOcr(recipe.id,images);
  return{recipe,images};
};
beforeEach(async()=>{db.close();await db.delete();await db.open();createWorker.mockClear();recognize.mockReset();terminate.mockClear()});

describe("local OCR boundary",()=>{
  it("does not load Tesseract until the user-triggered enqueue call",async()=>{const {recipe,image}=await setup();await getOrCreateOcrRecord(recipe.id,image.id);expect(createWorker).not.toHaveBeenCalled();recognize.mockResolvedValue({data:{text:"家常鸡腿\n鸡腿 500 g\n1、烤 20 分钟"}});const record=await enqueueOcr(recipe.id,image.id,image.blob,"chi_sim+eng");expect(createWorker).toHaveBeenCalledWith("chi_sim+eng",undefined,expect.anything());expect(record).toMatchObject({rawOcrText:"家常鸡腿\n鸡腿 500 g\n1、烤 20 分钟",editedOcrText:"家常鸡腿\n鸡腿 500 g\n1、烤 20 分钟",status:"completed",parserResult:{ingredients:[{normalizedLine:"鸡腿 500 g"}],steps:[{normalizedLine:"1、烤 20 分钟"}]}});await saveOcrRecord({...record,editedOcrText:"用户编辑"});expect(await db.ocrRecords.get(record.id)).toMatchObject({rawOcrText:"家常鸡腿\n鸡腿 500 g\n1、烤 20 分钟",editedOcrText:"用户编辑"})});
  it("keeps the screenshot when recognition fails and can retry that item",async()=>{const {recipe,image}=await setup();recognize.mockRejectedValueOnce(new Error("worker failed"));await expect(enqueueOcr(recipe.id,image.id,image.blob,"eng")).rejects.toThrow("worker failed");expect(await db.images.get(image.id)).toBeTruthy();expect(await db.ocrRecords.where("imageId").equals(image.id).first()).toMatchObject({status:"error"});recognize.mockResolvedValue({data:{text:"retry ok"}});await expect(enqueueOcr(recipe.id,image.id,image.blob,"eng")).resolves.toMatchObject({status:"completed",rawOcrText:"retry ok"})});
});

describe("multi-screenshot OCR queue",()=>{
  it("keeps direct enqueue calls globally sequential",async()=>{const {recipe,images}=await setupMany(3);let active=0,maxActive=0;recognize.mockImplementation(async()=>{active++;maxActive=Math.max(maxActive,active);await new Promise(resolve=>setTimeout(resolve,5));active--;return{data:{text:"ok"}}});await Promise.all(images.map(image=>enqueueOcr(recipe.id,image.id,image.blob,"eng")));expect(maxActive).toBe(1)});
  it.each([1,10,30])("creates one traceable record and processes %i screenshots sequentially",async count=>{const {recipe,images}=await setupMany(count);let active=0,maxActive=0;recognize.mockImplementation(async(blob:Blob)=>{active++;maxActive=Math.max(maxActive,active);await Promise.resolve();active--;return{data:{text:await blob.text()}}});const control={mode:"running" as const};const result=await runSequentialOcr({recipeId:recipe.id,images,language:"eng",control});expect(result).toMatchObject({completed:count,failed:0});expect(maxActive).toBe(1);const records=await db.ocrRecords.where("recipeId").equals(recipe.id).toArray();expect(records).toHaveLength(count);expect(new Set(records.map(record=>record.imageId)).size).toBe(count)});
  it("continues after one or multiple failures and supports retry",async()=>{const {recipe,images}=await setupMany(5);recognize.mockRejectedValueOnce(new Error("first")).mockResolvedValueOnce({data:{text:"ok"}}).mockRejectedValueOnce(new Error("third")).mockResolvedValue({data:{text:"ok"}});const control:{mode:"running"|"paused"|"cancelled"}={mode:"running"},first=await runSequentialOcr({recipeId:recipe.id,images,language:"eng",control});expect(first).toMatchObject({completed:3,failed:2});expect((await db.ocrRecords.where("recipeId").equals(recipe.id).toArray()).filter(record=>record.status==="error")).toHaveLength(2);recognize.mockResolvedValue({data:{text:"retried"}});control.mode="running";const retry=await runSequentialOcr({recipeId:recipe.id,images:images.filter(image=>true),language:"eng",control});expect(retry.failed).toBe(0);expect((await db.ocrRecords.where("recipeId").equals(recipe.id).toArray()).every(record=>record.status==="completed")).toBe(true)});
  it("pauses and cancels between items without losing completed text",async()=>{const {recipe,images}=await setupMany(10);recognize.mockResolvedValue({data:{text:"done"}});const control:{mode:"running"|"paused"|"cancelled"}={mode:"running"};await runSequentialOcr({recipeId:recipe.id,images,language:"eng",control,onComplete:index=>{if(index===0)control.mode="paused"}});let records=await db.ocrRecords.where("recipeId").equals(recipe.id).toArray();expect(records.filter(record=>record.status==="completed")).toHaveLength(1);expect(records.filter(record=>record.status==="not_started")).toHaveLength(9);control.mode="running";await runSequentialOcr({recipeId:recipe.id,images,language:"eng",control,onComplete:index=>{if(index===2)control.mode="cancelled"}});records=await db.ocrRecords.where("recipeId").equals(recipe.id).toArray();expect(records.filter(record=>record.status==="completed").length).toBeGreaterThan(1);expect(records.filter(record=>record.status==="not_started").length).toBeGreaterThan(0);control.mode="running";await runSequentialOcr({recipeId:recipe.id,images,language:"eng",control});expect((await db.ocrRecords.where("recipeId").equals(recipe.id).toArray()).every(record=>record.status==="completed")).toBe(true)});
  it("recovers interrupted state and builds an ordered document with image boundaries",async()=>{const {recipe,images}=await setupMany(2),records=await db.ocrRecords.where("recipeId").equals(recipe.id).toArray(),first=records.find(record=>record.imageId===images[0].id)!,second=records.find(record=>record.imageId===images[1].id)!;await db.ocrRecords.update(first.id,{status:"recognizing",rawOcrText:"第一张",editedOcrText:"编辑后的第一张"});await db.ocrRecords.update(second.id,{status:"completed",rawOcrText:"第二张",editedOcrText:"第二张"});await recoverInterruptedOcr(recipe.id);expect((await db.ocrRecords.get(first.id))?.status).toBe("not_started");const document=await combinedOcrDocument(recipe.id);expect(document).toContain("截图 1 [image:"+images[0].id+"]");expect(document.indexOf("编辑后的第一张")).toBeLessThan(document.indexOf("第二张"));expect(document).toContain("截图 2 [image:"+images[1].id+"]")});
  it("builds AI input from edited text for 10 images and excludes empty/raw-only records",async()=>{const {recipe,images}=await setupMany(10),records=await db.ocrRecords.where("recipeId").equals(recipe.id).toArray();for(const [index,image] of images.entries()){const record=records.find(item=>item.imageId===image.id)!;await db.ocrRecords.update(record.id,{rawOcrText:`raw ${index}`,editedOcrText:index===4?"":`confirmed ${index}`})}const text=await confirmedCombinedOcrText(recipe.id);expect(text.match(/--- 截图/g)).toHaveLength(9);expect(text).toContain("confirmed 9");expect(text).not.toContain("raw 4");expect(text.indexOf("confirmed 0")).toBeLessThan(text.indexOf("confirmed 9"))});
  it("detects exact duplicate screenshot bytes locally",async()=>{const first=new Blob(["same"]),second=new Blob(["same"]),third=new Blob(["different"]);expect(await screenshotHash(first)).toBe(await screenshotHash(second));expect(await screenshotHash(first)).not.toBe(await screenshotHash(third))});
});
