import {useMemo,useState} from "react";
import {approximateFraction,bakingPanSizes,butterEquivalents,convertRecipeText,equivalents,exactConvert,formatKitchenNumber,ingredientDensities,KITCHEN_CONSTANTS,type RecipeReadingMode,type ToolCategory,type Unit,unitsByCategory} from "../../lib/kitchen-tools";
import {addFavoriteConversion,addRecentConversion,clearSavedConversions,deleteSavedConversion,getFavoriteConversions,getRecentConversions,type SavedConversion} from "../services/kitchen-history";

const labels:Record<Exclude<ToolCategory,"butter"|"baking"|"recipe">,string>={temperature:"温度",weight:"重量",volume:"容量",length:"长度"};
const copy=(value:string)=>navigator.clipboard?.writeText(value);
const id=()=>crypto.randomUUID?.()??`${Date.now()}-${Math.random()}`;

export function KitchenTools({onClose,onInsertIngredient,onInsertStep}:{onClose?:()=>void;onInsertIngredient?:(value:string)=>void;onInsertStep?:(value:string)=>void}){
 const [category,setCategory]=useState<"temperature"|"weight"|"volume"|"length">("temperature"),[input,setInput]=useState("180"),[unit,setUnit]=useState<Unit>("°C"),[message,setMessage]=useState(""),[mode,setMode]=useState<RecipeReadingMode>("cn-us"),[recipeText,setRecipeText]=useState(""),[converted,setConverted]=useState(""),[previous,setPrevious]=useState<string|null>(null),[sticks,setSticks]=useState("1"),[recent,setRecent]=useState(getRecentConversions),[favorites,setFavorites]=useState(getFavoriteConversions);
 const numeric=Number(input),valid=input.trim()!==""&&Number.isFinite(numeric),results=useMemo(()=>valid?equivalents(numeric,unit):[],[numeric,unit,valid]),primary=results[0],display=valid&&primary?`${formatKitchenNumber(numeric)} ${unit} = ${primary.display}`:"";
 const units=[...unitsByCategory[category]] as Unit[];
 function selectCategory(next:typeof category){setCategory(next);setUnit(unitsByCategory[next][0]);setInput(next==="temperature"?"180":"1");setMessage("")}
 function saveRecent(category:ToolCategory,input:string,output:string){if(!output)return;setRecent(addRecentConversion({id:id(),category,input,output,createdAt:new Date().toISOString()}))}
 function saveFavorite(category:ToolCategory,input:string,output:string){if(!output)return;setFavorites(addFavoriteConversion({id:id(),category,input,output,createdAt:new Date().toISOString()}));setMessage("已加入收藏")}
 function reuse(item:SavedConversion){if(item.category==="recipe"){setRecipeText(item.input);setConverted(item.output);setMessage("已载入菜谱转换");return}if(["temperature","weight","volume","length"].includes(item.category)){const next=item.category as typeof category,set=([...unitsByCategory[next]] as Unit[]).find(candidate=>item.input.endsWith(` ${candidate}`));setCategory(next);if(set){setUnit(set);setInput(item.input.slice(0,-set.length).trim())}}setMessage(`已载入：${item.output}`)}
 function swap(){if(!primary)return;setInput(formatKitchenNumber(primary.value,8));setUnit(primary.unit)}
 function convertBlock(){if(!recipeText.trim()){setMessage("请先粘贴菜谱文字");return}const next=convertRecipeText(recipeText,mode);setPrevious(converted);setConverted(next);saveRecent("recipe",recipeText,next);setMessage("已生成预览，原文没有被修改")}
 const shell=onClose?"kitchen-tools-overlay":"";
 return <section className={`kitchen-tools ${shell}`} aria-label="厨房工具">{onClose&&<header className="kitchen-tools-modal-head"><button type="button" onClick={onClose}>关闭</button><h2>厨房工具</h2><span/></header>}
  <nav className="tool-jump" aria-label="工具分类">{(["temperature","weight","volume","length"] as const).map(value=><button type="button" aria-pressed={category===value} key={value} onClick={()=>selectCategory(value)}>{labels[value]}</button>)}<a href="#recipe-mode">菜谱模式</a><a href="#baking-tools">烘焙</a><a href="#butter-tools">黄油</a><a href="#reference">参考</a></nav>
  <section className="tool-card converter-card"><h2>{labels[category]}换算</h2><div className="converter-input"><label>数值<input inputMode="decimal" value={input} onChange={event=>setInput(event.target.value)} aria-invalid={input.trim()!==""&&!valid}/></label><label>单位<select value={unit} onChange={event=>setUnit(event.target.value as Unit)}>{units.map(value=><option key={value}>{value}</option>)}</select></label></div>{input.trim()!==""&&!valid&&<p className="error">请输入有效数字</p>}<div className="conversion-results">{valid&&<p className="primary-result">{formatKitchenNumber(numeric)} {unit}</p>}{results.map(result=><p key={result.unit}>{result.display}{(result.unit.includes("cup")||result.unit.includes("tbsp")||result.unit.includes("tsp"))&&approximateFraction(result.value)&&<small>约 {approximateFraction(result.value)}</small>}</p>)}</div><div className="tool-actions"><button type="button" onClick={swap} disabled={!primary}>交换单位</button><button type="button" onClick={()=>{void copy(display);saveRecent(category,`${input} ${unit}`,display)}} disabled={!display}>复制结果</button><button type="button" onClick={()=>{setInput("");setMessage("")}}>清除</button><button type="button" onClick={()=>{saveRecent(category,`${input} ${unit}`,display);saveFavorite(category,`${input} ${unit}`,display)}} disabled={!display}>收藏</button></div>{display&&<RecipeInsertActions value={display.replace(" = "," / ")} ingredient={category==="weight"||category==="volume"} onIngredient={onInsertIngredient} onStep={onInsertStep}/>}</section>
  <section className="tool-card" id="recipe-mode"><h2>中国 ↔ 美国菜谱模式</h2><div className="mode recipe-mode"><button type="button" className={mode==="cn-us"?"on":""} onClick={()=>setMode("cn-us")}>中国菜谱 → 美国阅读</button><button type="button" className={mode==="us-cn"?"on":""} onClick={()=>setMode("us-cn")}>美国菜谱 → 中国阅读</button></div><label>原始菜谱文字<textarea value={recipeText} onChange={event=>setRecipeText(event.target.value)} placeholder="粘贴整段菜谱，原文会始终保留……"/></label><div className="tool-actions"><button type="button" className="primary" onClick={convertBlock}>预览转换</button><button type="button" onClick={()=>copy(converted)} disabled={!converted}>复制转换文字</button><button type="button" onClick={()=>{setConverted(previous??"");setPrevious(null);setMessage("已撤销上一次转换")}} disabled={previous===null}>撤销</button></div>{converted&&<div className="recipe-conversion-preview"><h3>转换预览</h3><pre>{converted}</pre><RecipeInsertActions value={converted} ingredient onIngredient={onInsertIngredient} onStep={onInsertStep}/></div>}</section>
  <section className="tool-card" id="baking-tools"><h2>烘焙模具尺寸</h2><p>本阶段只换算尺寸，不自动按面积调整配方。</p><div className="reference-grid">{bakingPanSizes.map(size=><button type="button" key={size.label} onClick={()=>copy(`${size.label} = ${size.other}`)}><b>{size.label}</b><span>{size.other}</span></button>)}</div></section>
  <ButterTool sticks={sticks} setSticks={setSticks} onFavorite={value=>saveFavorite("butter",`${sticks} stick`,value)}/>
  <section className="tool-card" id="reference"><h2>厨房速查</h2><dl className="reference-list"><div><dt>1 US cup</dt><dd>{KITCHEN_CONSTANTS.usCupMl} ml</dd></div><div><dt>1 US tbsp</dt><dd>{formatKitchenNumber(KITCHEN_CONSTANTS.usTbspMl)} ml</dd></div><div><dt>1 US tsp</dt><dd>{formatKitchenNumber(KITCHEN_CONSTANTS.usTspMl)} ml</dd></div><div><dt>1 US fl oz</dt><dd>{formatKitchenNumber(KITCHEN_CONSTANTS.usFlOzMl)} ml</dd></div><div><dt>1 lb</dt><dd>{formatKitchenNumber(KITCHEN_CONSTANTS.lbG)} g</dd></div><div><dt>1 oz</dt><dd>{formatKitchenNumber(KITCHEN_CONSTANTS.ozG)} g</dd></div><div><dt>1 in</dt><dd>2.54 cm</dd></div><div><dt>1 stick butter</dt><dd>≈ 113.4 g</dd></div></dl></section>
  <section className="tool-card"><h2>食材 cup ↔ gram</h2><p>必须使用食材专属密度，绝不提供通用 cup 与 gram 换算。以下项目等待可靠来源确认后才会启用。</p><div className="density-list">{ingredientDensities.map(item=><span key={item.id}>{item.name}<small>待确认</small></span>)}</div></section>
  <SavedList title="最近换算" items={recent} onReuse={reuse} onCopy={item=>copy(item.output)} onDelete={item=>setRecent(deleteSavedConversion("recent",item.id))} onClear={()=>setRecent(clearSavedConversions("recent"))}/>
  <SavedList title="收藏" items={favorites} onReuse={reuse} onCopy={item=>copy(item.output)} onDelete={item=>setFavorites(deleteSavedConversion("favorite",item.id))} onClear={()=>setFavorites(clearSavedConversions("favorite"))}/>
  {message&&<p className="tool-message" role="status">{message}</p>}
 </section>
}

function RecipeInsertActions({value,ingredient,onIngredient,onStep}:{value:string;ingredient?:boolean;onIngredient?:(value:string)=>void;onStep?:(value:string)=>void}){if(!onIngredient&&!onStep)return null;return <div className="recipe-insert-actions">{ingredient&&onIngredient&&<button type="button" onClick={()=>onIngredient(value)}>插入食材</button>}{onStep&&<button type="button" onClick={()=>onStep(value)}>插入步骤</button>}</div>}
function ButterTool({sticks,setSticks,onFavorite}:{sticks:string;setSticks:(value:string)=>void;onFavorite:(value:string)=>void}){const n=Number(sticks),valid=sticks.trim()!==""&&Number.isFinite(n),result=valid?butterEquivalents(n):null,output=result?`${formatKitchenNumber(result.sticks)} stick = ${formatKitchenNumber(result.ounces)} oz / ${formatKitchenNumber(result.grams)} g / ${formatKitchenNumber(result.tablespoons)} US tbsp`:"";return <section className="tool-card" id="butter-tools"><h2>黄油换算</h2><label>黄油棒数<input inputMode="decimal" value={sticks} onChange={event=>setSticks(event.target.value)}/></label>{result&&<p className="primary-result">{output}</p>}<div className="tool-actions"><button type="button" onClick={()=>copy(output)} disabled={!output}>复制</button><button type="button" onClick={()=>onFavorite(output)} disabled={!output}>收藏</button></div></section>}
function SavedList({title,items,onReuse,onCopy,onDelete,onClear}:{title:string;items:SavedConversion[];onReuse:(item:SavedConversion)=>void;onCopy:(item:SavedConversion)=>void;onDelete:(item:SavedConversion)=>void;onClear:()=>void}){return <section className="tool-card saved-conversions"><div className="saved-head"><h2>{title}</h2><button type="button" onClick={onClear} disabled={!items.length}>清空</button></div>{items.length?items.map(item=><article key={item.id}><div><b>{item.input}</b><p>{item.output}</p></div><div><button type="button" onClick={()=>onReuse(item)}>复用</button><button type="button" onClick={()=>onCopy(item)}>复制</button><button type="button" onClick={()=>onDelete(item)}>删除</button></div></article>):<p>暂无记录</p>}</section>}
